In [ ]:
1.

Parašykite programą, kuri išsprendžia lygčių sistemą ir suapvalintą atsakymą išveda stulpeliu.

Pirmoje eilutėje pateikti du skaičiai n ir m:
n - lygčių skaičius,
m - nežinomųjų skaičius.
Toliau n eilučių, kiekvienoje eilutėje m+1 skaičius. Pirmi m skaičių - tai lygties nežinomųjų koeficientai, paskutinis skaičius - lygties rezultatas.


4 4
1 2 -1 1 -3
3 3 -5 2 -7
-3 1 4 -5 5
1 3 -2 1 -5


1.0
-1.0
1.0
-1.0


In [8]:
import numpy as np
n,m = map(int, input().split())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))

v1 = np.array(v1)
data = np.delete(v1,len(v1[0])-1, axis=1)
answers = np.array(v1[:,-1])

solution = np.linalg.solve(data,answers)
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})

for x in solution:
    print(np.round(x,1))



LinAlgError: Last 2 dimensions of the array must be square

2.

Parašykite programą, kuri išsprendžia matricinę lygtį A*x = B

n - matricos dimensija
Kvadratinės matricos A ir B

3
1 0 3
1 -4 1
-2 3 -5
10 -7 -10
-14 -3 18
-4 12 1


[[-2. -1. 2.]
[ 4. -0. -5.]
[ 4. -2. -4.]]


In [46]:
import numpy as np
n = int(input())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))
v1 = np.array(v1)

v2 = []
for i in range(n):
    v2.append(list(map(int, input().split())))
v2 = np.array(v2)


X = np.linalg.solve(v1, v2)
print(X)


[[-2.0 -1.0  2.0]
 [ 4.0 -0.0 -5.0]
 [ 4.0 -2.0 -4.0]]


3.

Parašykite programą, kuri išsprendžia matricinę lygtį x*A = B.

n - matricos dimensija
Kvadratinės matricos A ir B

3
5 2 -4
-5 -5 -5
0 -1 -2
0 3 6
25 5 -30
-5 -3 -1

[[ 0. 0. -3.]
[ 5. -0. 5.]
[-0. 1. -2.]]


In [48]:
#https://stackoverflow.com/questions/52826206/solve-linear-equation-in-python-xa-b
import numpy as np
n = int(input())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))
v1 = np.array(v1)

v2 = []
for i in range(n):
    v2.append(list(map(int, input().split())))
v2 = np.array(v2)


X = np.round(np.matmul(v2, np.linalg.inv(v1)), decimals=1)
print(X)


[[ 70.0  37.0 -26.0]
 [-100.0 -25.0  125.0]
 [-15.0  1.0  32.0]]


4.

Iš failo duom.txt nuskaitykite ir išveskite masyvą. Pakeiskite masyvo reikšmes inf reikšmėmis 100, o reikšmes nan reikšmėmis -10. Rezultatą įrašykite į failą rez.txt.


1 nan 3
4 5 6
7 8 inf


1 -10 3
4 5 6
7 8 100

In [19]:
import numpy as np
a1 = np.loadtxt('duom.txt',dtype=np.float)
a1[np.isinf(a1)] = 100
a1[np.isnan(a1)] = -10
a1 = np.array(a1, dtype=np.int8)

f = open('rez.txt', 'w')
for line in a1:
    printString = ''
    for x in line:
        printString += str(x) + ' '
    f.write(printString[:-1] + "\n")
f.close()


C:\Users\laimo\AppData\Local\Temp/ipykernel_26228/387539627.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a1 = np.loadtxt('duom.txt',dtype=np.float)
