In [ ]:
1.

Duotas masyvas a.
Iš masyvo a pašalinkite inf, -inf ir nan reikšmes.

10, 20, np.NINF, np.nan, np.inf

[10. 20.]

In [11]:
import numpy as np
np.set_printoptions(suppress=True)

a = np.array(eval(input()))

while np.isnan(a).any() or np.isinf(a).any():
    a = np.delete(a, np.where(np.isnan(a)))
    a = np.delete(a, np.where(np.isinf(a)))
print(a)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2.

Duotas masyvas (4x4). Išveskite antrą pagal dydį vertę.

9 4 2 1
0 9 3 7
1 9 0 2
3 4 2 6

7


In [12]:
import numpy as np
np.set_printoptions(suppress=True)

a = []
for i in range(4):
    a.append(list(map(int, input().split())))
a = np.array(a, dtype=float)
flat = np.unique(a)
flat.sort()
print(int(flat[-2]))


7.0


3.

Duotas masyvas (4x4).
Išveskite pirmo elemento, kurio vertė >3 kordinates

2 4 1 3
4 3 3 2
4 0 2 0
0 4 4 2

0 1

In [20]:
import numpy as np
import sys
np.set_printoptions(suppress=True)

a = []
for i in range(4):
    a.append(list(map(int, input().split())))
a = np.array(a, dtype=np.int8)

for row, i in enumerate(a):
    for column, j in enumerate(i):
        if j > 3:
            print(f"{row} {column}")
            sys.exit()


0
[2 4 1 3]
0 1


SystemExit: 

C:\Users\laimo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


4.

Duotas masyvas a (3x5).
Surūšiuokite eilutes taip, kad trečio stulpelio elementai būtų išdėstyti didėjimo tvarka.

5 0 1 3 2
-3 2 9 4 8
-1 6 3 1 3



[[ 5. 0. 1. 3. 2.]
[-1. 6. 3. 1. 3.]
[-3. 2. 9. 4. 8.]]

In [25]:
import numpy as np
import sys
np.set_printoptions(suppress=True)

a = []
for i in range(3):
    a.append(list(map(int, input().split())))
a = np.array(a, dtype=float)

print(a[a[:, 2].argsort()])




[[5. 0. 1. 3. 2.]
 [5. 0. 3. 3. 2.]
 [5. 0. 7. 3. 2.]]


5.

Parašykite programą, kuri surūšiuoti vardų (first_names) ir pavardžių (last_names) poras (pirmiausia pagal pavardę, po to pagal vardą).
Išveskite surūšiuotas poras.

first_names, last_names

("Margery","Betsey","Shelley","Lanell","Genesis","Andy")
("Woolum","Battle","Plotner","Brien","Stahl","Battle")

Battle Andy
Battle Betsey
Brien Lanell
Plotner Shelley
Stahl Genesis
Woolum Margery

In [53]:
import numpy as np
import sys
np.set_printoptions(suppress=True)

first_names = np.array(eval(input()))
last_names = np.array(eval(input()))

arr_type = [('last_names', 'U10'), ('first_names', 'U10')]
arr=np.ones(len(first_names), dtype=arr_type)
arr['first_names'] = first_names
arr['last_names'] = last_names
arr = np.sort(arr, order='last_names')
for i in arr:
    print(*i)


SyntaxError: unexpected EOF while parsing (<string>, line 0)