In [ ]:
1.

Parašykite NumPy programą, kad sukurtumėte dvimatį masyvą (nxn) su 1 kraštuose ir 0 viduje.

4

[[1. 1. 1. 1.]
[1. 0. 0. 1.]
[1. 0. 0. 1.]
[1. 1. 1. 1.]]

In [1]:
import numpy as np
n = int(input())
x = np.ones((n,n))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


2.

Duotas masyvas a.
Išveskite vienetų ir nulių skaičius.


0 0 1 2 1 1 0 0 0

vienetu - 3
nuliu - 5

In [8]:
import numpy as np
v1 = list(map(float, input().split()))
v2 = np.tile(v1, [4,1])
print(np.triu(np.tril(v1)))

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


4.

Duotas masyvas. Pakeiskite reikšmes > 5 reikšme 5

1 3 5 7 9
[1 3 5 5 5]

In [11]:
import numpy as np
v1 = np.array(list(map(int, input().split())))
v2 = np.where((v1 < 5), v1, 5)
print(v2)

[1. 3. 5. 5. 5.]


5.

Duotas skaičius n.
Sukurkite nulių masyvą a(nxn) ir parašykite programą, kuri pakeičia masyvo reikšmes taip, kaip parodyta

4

[[0. 1. 2. 3.]
[0. 1. 2. 3.]
[0. 1. 2. 3.]
[0. 1. 2. 3.]]

In [14]:
import numpy as np
n = int(input())
v1 = np.arange(n)
v2 = np.tile(v1, [n,1])
print(np.array(v2,dtype=float))

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


6.

Duotas masyvas a.
Parašykite programą, kuri apskaičiuoja ir išveda elementų, kurie dalijasi iš 5 ir nesidalija iš 2 sandaugą.


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

75



In [22]:
import numpy as np
a = np.array(list(map(float, input().split())))
suma = 1
for i in a.flat:
    if i % 5 == 0 and i % 2 != 0:
        suma *= i

print(int(suma))

75


7.

Duotas vienmatis masyvas a. Išveskite elementų, kurių reikšmė > 25, skaičių.

43 2 12 28 40 37 28 23 25 46

6

In [26]:
import numpy as np
a = np.array(list(map(float, input().split())))
print(len([element for element in a if element > 25]))

6


8.

Duotas masyvas a Viena komanda pašalinkite iš jo elementus su indeksais duotais masyve b.

100 101 102 103 104 105 106 107 108 109 110
2 3 4 5

[100 101 106 107 108 109 110]

In [27]:
import numpy as np
a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))
print(np.delete(a,b))


[100 101 106 107 108 109 110]


9.

Duotas dvimatis masyvas (nxn).
Pašalinkite stulpelius, kuriose yra nan reikšmė.

4
np.nan 2 3 4
5 6 7 8
9 10 11 np.nan
13 14 15 16

[[ 2. 3.]
[ 6. 7.]
[10. 11.]
[14. 15.]]

In [65]:
import numpy as np
import sys
np.set_printoptions(suppress=True)

n = int(input())
a = []
for i in range(n):
    inp = input().split()
    a.append(inp)
a = np.array(a)
a = np.where((a == 'np.nan'), np.nan, a)
a = np.array(a, dtype=float)

print(a[:, ~np.isnan(a).any(axis=0)])


[[2. 3. 4.]
 [2. 3. 4.]
 [6. 7. 8.]
 [6. 7. 8.]]


10.

Sukurkite universalią funkciją (ufunc), kuri turi du parametrus a ir b.
Kur
a – dvimatis masyvas (nxn);
b – arba skaičius (1), arba vienmatis masyvas (2), arba dvimatis masyvas (3)
Funkcija grąžina masyvą, kur kiekvienas elementas apskaičiuojamas kaip paelementinio skirtumo modulis |a - b|.

n - a masyvo dimensijos
a
skaicius 1, 2 arba 3, kuris nusako kokio tipo bus b
b


3
1 2 3
4 5 6
7 8 9
1
5


[[4. 3. 2.]
[1. 0. 1.]
[2. 3. 4.]]


In [71]:
import numpy as np
np.set_printoptions(suppress=True)

def ufunc(a, b):
    return np.abs(a - b)

n = int(input())
v1 = []
for i in range(n):
    v1.append(list(map(float, input().split())))
v1 = np.array(v1, dtype=float)

n2 = int(input())

if n2 == 1:
    v2 = int(input())
elif n2 == 2:
    v2 = list(map(float, input().split()))
elif n2 == 3:
    v2 = []
    for i in range(n):
        v2.append(list(map(float, input().split())))
    v2 = np.array(v2, dtype=float)

op = np.vectorize(ufunc)
print(op(v1, v2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


11.

Sukurkite masyvą a(nxn), kuriame pagrindinėje įstrižainėje yra trejetai (3), pirmoje įstrižainėje virš pagrindinės – vienetai (1), visi kiti – nuliai (0)

4

[[3. 1. 0. 0.]
[0. 3. 1. 0.]
[0. 0. 3. 1.]
[0. 0. 0. 3.]]

In [76]:
import numpy as np
np.set_printoptions(suppress=True)

n = int(input())
v1 = np.eye(n) * 3
v2 = np.eye(n,k=1)

print(v1 + v2)

[[3. 1. 0. 0.]
 [0. 3. 1. 0.]
 [0. 0. 3. 1.]
 [0. 0. 0. 3.]]
