In [ ]:
1.

Parašykite programą, kuri išsprendžia lygčių sistemą ir suapvalintą atsakymą išveda stulpeliu.

Pirmoje eilutėje pateikti du skaičiai n ir m:
n - lygčių skaičius,
m - nežinomųjų skaičius.
Toliau n eilučių, kiekvienoje eilutėje m+1 skaičius. Pirmi m skaičių - tai lygties nežinomųjų koeficientai, paskutinis skaičius - lygties rezultatas.


4 4
1 2 -1 1 -3
3 3 -5 2 -7
-3 1 4 -5 5
1 3 -2 1 -5


1.0
-1.0
1.0
-1.0


In [22]:
import numpy as np
n,m = map(int, input().split())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))

v1 = np.array(v1)
data = np.delete(v1,len(v1[0])-1, axis=1)
answers = np.array(v1[:,-1])

solution = np.linalg.lstsq(data, answers)[0]
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})

for x in solution:
    print(np.round(x,1))



1.0


C:\Users\laimo\AppData\Local\Temp/ipykernel_26228/4070178240.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution = np.linalg.lstsq(data, answers)[0]


2.

Parašykite programą, kuri išsprendžia matricinę lygtį A*x = B

n - matricos dimensija
Kvadratinės matricos A ir B

3
1 0 3
1 -4 1
-2 3 -5
10 -7 -10
-14 -3 18
-4 12 1


[[-2. -1. 2.]
[ 4. -0. -5.]
[ 4. -2. -4.]]


In [46]:
import numpy as np
n = int(input())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))
v1 = np.array(v1)

v2 = []
for i in range(n):
    v2.append(list(map(int, input().split())))
v2 = np.array(v2)


X = np.linalg.solve(v1, v2)
print(X)


[[-2.0 -1.0  2.0]
 [ 4.0 -0.0 -5.0]
 [ 4.0 -2.0 -4.0]]


3.

Parašykite programą, kuri išsprendžia matricinę lygtį x*A = B.

n - matricos dimensija
Kvadratinės matricos A ir B

3
5 2 -4
-5 -5 -5
0 -1 -2
0 3 6
25 5 -30
-5 -3 -1

[[ 0. 0. -3.]
[ 5. -0. 5.]
[-0. 1. -2.]]


In [48]:
#https://stackoverflow.com/questions/52826206/solve-linear-equation-in-python-xa-b
import numpy as np
n = int(input())
v1 = []
for i in range(n):
    v1.append(list(map(int, input().split())))
v1 = np.array(v1)

v2 = []
for i in range(n):
    v2.append(list(map(int, input().split())))
v2 = np.array(v2)


X = np.round(np.matmul(v2, np.linalg.inv(v1)), decimals=1)
print(X)


[[ 70.0  37.0 -26.0]
 [-100.0 -25.0  125.0]
 [-15.0  1.0  32.0]]


4.

Iš failo duom.txt nuskaitykite ir išveskite masyvą. Pakeiskite masyvo reikšmes inf reikšmėmis 100, o reikšmes nan reikšmėmis -10. Rezultatą įrašykite į failą rez.txt.


1 nan 3
4 5 6
7 8 inf


1 -10 3
4 5 6
7 8 100

In [19]:
import numpy as np
a1 = np.loadtxt('duom.txt',dtype=np.float)
a1[np.isinf(a1)] = 100
a1[np.isnan(a1)] = -10
a1 = np.array(a1, dtype=np.int8)

f = open('rez.txt', 'w')
for line in a1:
    printString = ''
    for x in line:
        printString += str(x) + ' '
    f.write(printString[:-1] + "\n")
f.close()


C:\Users\laimo\AppData\Local\Temp/ipykernel_26228/387539627.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a1 = np.loadtxt('duom.txt',dtype=np.float)


5.

Duota matrica a(n x n) ir vienmatis masyvas b(1 x n). Parašykite programą, kuri pakelia kiekvienos eilutės elementą atitinkamu laipsniu (iš masyvo b).


4
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16
2 2 3 3

[[ 1. 4. 27. 64.]
[ 25. 36. 343. 512.]
[ 81. 100. 1331. 1728.]
[ 169. 196. 3375. 4096.]]


In [7]:
import numpy as np
n = int(input())
a = []
for i in range(n):
    a.append(list(map(int, input().split())))
a = np.array(a)

np.set_printoptions(suppress = True)
b = list(map(int, input().split()))
print(np.array(np.power(a,b), dtype=np.float64))


[[  1.   4.  27. 256.]
 [  1.   4.  27. 256.]
 [  1.   4.  27. 256.]
 [  1.   4.  27. 256.]]


6.

Sukurkite universalią dviejų parametrų funkciją. Pirmas parametras (a) – dvimatis masyvas, antras (b) – vienmatis arba dvimatis masyvas. Funkcija turi grąžinti dvimatį masyvą. Jeigu pirmo ir antro masyvų elemento reikšmės lygios, grąžina -1. Jeigu pirmo masyvo elemento reikšmė didesnė – grąžinama reikšmių dalybos liekana (aJeigu pirmo masyvo elemento reikšmė mažesnė – grąžinama reikšmių sandauga (a*b).

n - a masyvo eilučių skaičius masyvas a m - b masyvo eilučių skaičius masyvas b

a ir b masyvo stulpelių skaičius visada lygus n


6.

Sukurkite universalią dviejų parametrų funkciją. Pirmas parametras (a) – dvimatis masyvas, antras (b) – vienmatis arba dvimatis masyvas. Funkcija turi grąžinti dvimatį masyvą. Jeigu pirmo ir antro masyvų elemento reikšmės lygios, grąžina -1. Jeigu pirmo masyvo elemento reikšmė didesnė – grąžinama reikšmių dalybos liekana (aJeigu pirmo masyvo elemento reikšmė mažesnė – grąžinama reikšmių sandauga (a*b).

n - a masyvo eilučių skaičius masyvas a m - b masyvo eilučių skaičius masyvas b

a ir b masyvo stulpelių skaičius visada lygus n


3
1 2 3
4 5 6
7 8 9
1
1 2 10

[[-1. -1. 30.]
[ 0. 1. 60.]
[ 0. 0. 90.]]



In [13]:
import numpy as np
np.set_printoptions(suppress=True)

def operation(a, b):
    if a == b:
        return -1
    elif a > b:
        return a%b
    elif a < b:
        return a*b

n1 = int(input())
v1 = []
for i in range(n1):
    v1.append(list(map(float, input().split())))
v1 = np.array(v1, dtype=float)

n2 = int(input())
v2 = []
for i in range(n2):
    v2.append(list(map(float, input().split())))
v2 = np.array(v2, dtype=float)

op = np.vectorize(operation)
print(np.array(op(v1, v2), dtype=float))

[[-1. -1. 30.]
 [ 0.  1. 60.]
 [ 1.  0. 90.]]


7.

Duotas dvimatis masyvas a. Ciklo for pagalba modifikuokite masyvą, apskaičiuodami kiekvieno elemento kubą.


3 4
10 11 12 13
14 15 16 17
18 19 20 21

[[1000. 1331. 1728. 2197.]
[2744. 3375. 4096. 4913.]
[5832. 6859. 8000. 9261.]]



In [16]:
import numpy as np
np.set_printoptions(suppress=True)

n,m = map(int, input().split())
v1 = []
for i in range(n):
    v1.append(list(map(float, input().split())))
v1 = np.array(v1, dtype=float)

for i in np.nditer(v1,op_flags=['readwrite']): 
    i[...] = i ** 3
print(v1)


[[1000. 1331. 1728. 2197.]
 [2744. 3375. 4096. 4913.]
 [5832. 6859. 8000. 9261.]]


8.

Duotas masyvas a(4x4) ir masyvas b = (1x4). Funkcijos where() pagalba atrinkite masyvo a reikšmes (a[i][j] < 5) ir pakelkite jas atitinkamu laipsniu (iš masyvo b). Kitas reikšmes padauginkite iš 5.


0 6 2 4
9 1 4 3
1 3 4 8
3 1 8 8
2 3 4 5


[[ 0. 30. 16. 1024.]
[ 45. 1. 256. 243.]
[ 1. 27. 256. 40.]
[ 9. 1. 40. 40.]]

In [21]:
import numpy as np
np.set_printoptions(suppress=True)

a = []
for i in range(4):
    a.append(list(map(float, input().split())))
a = np.array(a, dtype=float)

b = np.array(list(map(int, input().split())))

c = np.where(a<5, np.power(a, b), a*5)
print(c)


[[   0.   30.   16. 1024.]
 [  45.    1.  256.  243.]
 [   1.   27.  256.   40.]
 [   1.   27.  256.   40.]]


9. 

Duotas masyvas a(4x4). Išspausdinkite:

eilučių didžiausias reikšmes ir didžiausių reikšmių indeksus;
stulpelių mažiausias reikšmes ir mažiausių reikšmių indeksus;
visų elementų sumą;
visų elementų vidurkį.


31 45 48 13
44 17 24 14
40 27 25 49
32 33 68 71



48.0 44.0 49.0 71.0
2 0 3 3
31.0 17.0 24.0 13.0
0 1 1 0
581.0
36.3125

In [26]:
import numpy as np
np.set_printoptions(suppress=True)

a = []
for i in range(4):
    a.append(list(map(float, input().split())))
a = np.array(a, dtype=float)

maxnum = []
maxindex = []
minnum = []
minindex = []

for i in range(4):
    maxnum.append(np.max(a[i]))
    maxindex.append(np.argmax(a[i]))
    minnum.append(np.min(a[:,i]))
    minindex.append(np.argmin(a[:,i]))

print(*maxnum)
print(*maxindex)
print(*minnum)
print(*minindex)
print(np.sum(a))
print(np.mean(a))

48.0 44.0 49.0 71.0
2 0 3 3
31.0 17.0 24.0 13.0
0 1 1 0


10.

Duota kvadratinė matrica(4x4). Išspausdinkite:

stulpelių kaupiamąją elementų sandaugą
visų elementų kaupiamąją sandaugą
stulpelių kaimyninių elementų skirtumus.

1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16


[[ 1. 2. 3. 4.]
[ 6. 8. 10. 12.]
[15. 18. 21. 24.]
[28. 32. 36. 40.]]

[ 1. 3. 6. 10. 15. 21. 28. 36. 45. 55. 66. 78. 91. 105. 120. 136.]

[[4. 4. 4. 4.]
[4. 4. 4. 4.]
[4. 4. 4. 4.]]




In [33]:
import numpy as np
np.set_printoptions(suppress=True)

a = []
for i in range(4):
    a.append(list(map(int, input().split())))
a = np.array(a, dtype=float)

print(np.cumsum(a, axis=0))
print()
print(np.cumsum(a))
print()
print(np.diff(a, axis = 0))


[[ 1.  2.  3.  4.]
 [ 6.  8. 10. 12.]
 [15. 18. 21. 24.]
 [28. 32. 36. 40.]]

[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


11.

Duoti du masyvai a ir b. Išspausdinkite:

unikalias reikšmes, esančias abiejuose masyvuose;
unikalias antro masyvo reikšmes, kurių nėra pirmame masyve;
unikalias reikšmes, kurios yra tik viename (ne abiejuose) masyvuose.

1 2 3 4 5 6 7 8 9 10 11
2 4 6 8 10 12

[2, 4, 6, 8, 10]
[12]
[1, 3, 5, 7, 9, 11, 12]


In [43]:
import numpy as np
np.set_printoptions(suppress=True)

a = np.array(list(map(int, input().split())))
b = np.array(list(map(int, input().split())))
print(list(np.intersect1d(a,b)))
print(list(np.setdiff1d(b,a)))
print(list(np.setxor1d(a,b)))


[2, 4, 6, 8, 10]
[12]
[1, 3, 5, 7, 9, 11, 12]


12.

Duotas (nXn) masyvas. Nustatykite, ar masyve yra bent vienas nulinis elementas. Išveskite atitinkamą pranešimą.

4
4 5 8 7
-7 -7 -4 1
6 -5 -10 -5
4 1 9 1

nera 0


4
4 5 8 7
-7 0 -4 1
6 -5 -10 -5
4 1 9 1

yra 0

In [49]:
import numpy as np
np.set_printoptions(suppress=True)

n1 = int(input())
v1 = []
for i in range(n1):
    v1.append(list(map(float, input().split())))
v1 = np.array(v1, dtype=float)


a = np.where(v1 == 0)
if len(a[0]):
    print("yra 0")
else:
    print("nera 0")


yra 0
