In [16]:
class Egz:
    stat = 'statinis kint'
    def __init__(self, kint):
        self.kint = kint

    @classmethod
    def mcls(cls):
        cls.a = 11
        print('Parent class method')

    @staticmethod
    def mstat():
        print('Parent static method')

    def vienas(self):
        return self.kint * 5

    def __str__(self):
        return f'Overloaded {self.kint}'

    def m1(self, a = 10):
        return self.kint + a
    
    def m2(self, *a):
        return self.kint + sum(a)

e = Egz(10)
print(Egz.stat)
print(Egz.mcls())
print(e.a)
print(Egz.mstat())
print(e.vienas())
print(e.m1())
print(e.m2(100, 10 , 10))
print(str(e))

print('-------------')
print('-------------')
print('-------------')
print('-------------')

class Testas(Egz):
    def __init__(self, kint, antras):
        super().__init__(kint)
        self.antras = antras
        super().m1(antras)
        
t = Testas(10, 2)
print(t.kint)
print(t.antras)
print(t.vienas())

print('-------------')
print('-------------')
print('-------------')
print('-------------')

class Uzd(Egz):
    def __init__(self, kint, antras):
        super().__init__(kint)
        self.antras = antras
        super().m1(antras)
        
u = Uzd(5, 2)
print(u.kint)
print(u.antras)
print(u.vienas())

print('-------------')
print('-------------')
print('-------------')
print('-------------')

l = list([1,2,3,4,5])
a = {1,2,3,4,5}
d = {'a':1, 'b':2, 'c':3}
t = (1,2,3,4,5)

print(l, a, d, t, sep='\n')

print('-------------')
print('-------------')
print('-------------')
print('-------------')

print([x*x for x in range(5)])

print('-------------')
print('-------------')
print('-------------')
print('-------------')

inp = input().split(',')
print(inp)

print('-------------')
print('-------------')
print('-------------')
print('-------------')

d = {'x': 100, 'b': 100, 'e': 200, 'a': 300, 'h': 100, 'd': 100}
L = list(d.items())
print(L,'\n')
L.sort(key=lambda x: x[1])
print(L)

print('-------------')
print('-------------')
print('-------------')
print('-------------')

f = open('ats.txt', 'w')
f.write('Hello world!')
f.close()

print('-------------')
print('-------------')
print('-------------')
print('-------------')

import numpy as np
print(np.ones((3,3)))
print(np.eye(3,3))
print(np.full((3,3), 9))
print(np.tile(3, [5,5]))
print(np.random.randint(0, 30))




statinis kint
Parent class method
None
11
Parent static method
None
50
20
130
Overloaded 10
-------------
-------------
-------------
-------------
10
2
50
-------------
-------------
-------------
-------------
5
2
25
-------------
-------------
-------------
-------------
[1, 2, 3, 4, 5]
{1, 2, 3, 4, 5}
{'a': 1, 'b': 2, 'c': 3}
(1, 2, 3, 4, 5)
-------------
-------------
-------------
-------------
[0, 1, 4, 9, 16]
-------------
-------------
-------------
-------------
['1', '2', '3']
-------------
-------------
-------------
-------------
[('x', 100), ('b', 100), ('e', 200), ('a', 300), ('h', 100), ('d', 100)] 

[('x', 100), ('b', 100), ('h', 100), ('d', 100), ('e', 200), ('a', 300)]
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
5
